### ISSUE TITLE
Support QGIS 3+

### ISSUE THREAD

**Issue by JedStephens** [ArMoraer/QGISSortAndNumber#3]
This is a great plugin, thanks for the work!

Unfortunately, it is not supported on QGIS 3.0+. Would it be possible to extend support for it?

![image](https://user-images.githubusercontent.com/26483444/39693006-dee798a0-51e2-11e8-85ef-4e30e9663436.png)

I use it regularly in my research.

**Comment by JedStephens** [comment]
Perhaps of use.
https://github.com/qgis/QGIS/wiki/Plugin-migration-to-QGIS-3

**Comment by JedStephens** [comment]
This would also be of use:
https://github.com/opengisch/qgis2to3/

**Comment by ArMoraer** [comment]
Thanks for your interest and suggestions. I guess it should be easy to migrate to QGIS 3.0 since this plugin is quite simple! I'll have a look to this problem in the next weeks.

**Comment by sotaventoUY** [comment]
This is what I need on QGIS 3.03!!! 
Please, let me know as soon as you finish the migration.
Rgds

**Comment by ArMoraer** [comment]
Just to keep you updated: I'm currently working on it. It's a bit difficult because I currently don't have access to QGIS 3 so I can't really test from home, but I've committed a few updates that I will test at work next week.

**Comment by sotaventoUY** [comment]
Great, if you need a beta tester just let me know

**Comment by BCLdn** [comment]
Hi - I have just updated to the newest "stable" version - 3.4.6-Madeira. I use the Sort and Number plug-in extensively to generate maps, and, as per previous comments, the plugin isn't compatible. Has there been and further progress on making this available again? Would love to be able to use it with the newest version - otherwise I'll have to resort to going back to the old version. I've tried downloading and installing manually but to no avail! Any reply would be greatly appreciated. Thanks.

**Comment by ArMoraer** [comment]
Hi,
As you can guess I kind of completely forgot this issue :s 
But I have good news: I think I fixed the compatibility issue! I have uploaded a new version (1.0) to the QGIS plugin repository, so it should be possible to update the plugin from the plugin menu ~~in a few days~~ from now on. Version 1.0 is however not compatible with QGIS 2.x.
If you're in a hurry, you can still download the code from github and manually install the plugin.
Hope this will work.

**Comment by marsofearth** [comment]
Using QGIS 3.8, when I load your plugin, I am not seeing it anywhere.

**Comment by DavidHJong** [comment]
> Using QGIS 3.8, when I load your plugin, I am not seeing it anywhere.

In QGIS 3.10, it's in vector menu.

**Comment by DavidHJong** [comment]
I'm using QGIS 3.10, and I'd like to report some bugs. When I run this plugin, a new field is created with no value, and three error messages appear showing that three modules could not be found: grassplugin7.dll, grassprovider7.dll, and grassrasterprovider7.dll. And when I try to update an existing field, the software would freeze.

**Comment by JedStephens** [comment]
> I'm using QGIS 3.10, and I'd like to report some bugs. When I run this plugin, a new field is created with no value, and three error messages appear showing that three modules could not be found: grassplugin7.dll, grassprovider7.dll, and grassrasterprovider7.dll. And when I try to update an existing field, the software would freeze.

This sounds like a totally separate request. When I opened this issue it was because this useful plugin did yet support QGIS 3.**.  However you're reporting bug behavior. I'm going to close this issue and I hope you'll reopen your issue as a separate one with the bug tag.
